spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testexcel?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  id-type: 0